name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload artifact to S3
      run: |
        export AWS_REGION=ap-northeast-2
        export S3_BUCKET_NAME=elasticbeanstalk-ap-northeast-2-767397751289
        export APP_NAME=POPCONBOOTAPP
        export ENV_NAME=POPCONBOOTAPP-env-1
        export VERSION_LABEL=$GITHUB_SHA
        
        aws s3 cp target/*.jar s3://$S3_BUCKET_NAME/$APP_NAME-$VERSION_LABEL.jar --region $AWS_REGION

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $VERSION_LABEL --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key=$APP_NAME-$VERSION_LABEL.jar --region $AWS_REGION
        aws elasticbeanstalk update-environment --environment-name $ENV_NAME --version-label $VERSION_LABEL --region $AWS_REGION

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
